In [1]:
import pandas as pd
import numpy as np
import sklearn
import tensorflow as tf
import matplotlib.pyplot as plt

print("pandas:", pd.__version__)
print("numpy:", np.__version__)
print("sklearn:", sklearn.__version__)
print("tensorflow:", tf.__version__)

pandas: 3.0.2
numpy: 2.4.4
sklearn: 1.8.0
tensorflow: 2.21.0

In [2]:
import pandas as pd

df = pd.read_csv("../data/raw/quito_air_quality_sample.csv")
df.head()

,datetime,station,pm25,pm10,no2,o3,so2,co,temperature,humidity,aqi
0,2026-01-01 08:00,Centro,12,25,18,20,4,0.4,15,72,42
1,2026-01-01 09:00,Centro,18,30,20,22,5,0.5,16,70,55
2,2026-01-01 10:00,Centro,35,60,28,30,6,0.7,18,65,88
3,2026-01-01 11:00,Centro,55,90,40,38,8,0.9,19,60,120
4,2026-01-01 12:00,Cotocollao,10,20,15,19,3,0.3,17,75,38

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   datetime     10 non-null     str
 1   station      10 non-null     str
 2   pm25         10 non-null     int64
 3   pm10         10 non-null     int64
 4   no2          10 non-null     int64
 5   o3           10 non-null     int64
 6   so2          10 non-null     int64
 7   co           10 non-null     float64
 8   temperature  10 non-null     int64
 9   humidity     10 non-null     int64
 10  aqi          10 non-null     int64
dtypes: float64(1), int64(8), str(2)
memory usage: 1012.0 bytes

In [4]:
df.describe()

,pm25,pm10,no2,o3,so2,co,temperature,humidity,aqi
count,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000
mean,30.500000,52.800000,27.000000,27.900000,5.700000,0.610000,18.300000,66.800000,78.300000
std,18.343936,28.974318,10.198039,7.593126,1.888562,0.233095,1.888562,5.432413,33.741007
min,10.000000,20.000000,15.000000,19.000000,3.000000,0.300000,15.000000,58.000000,38.000000
25%,15.750000,28.500000,18.500000,21.250000,4.250000,0.425000,17.250000,63.500000,49.750000
50%,26.000000,47.500000,26.000000,27.500000,5.500000,0.550000,18.500000,67.000000,76.000000
75%,44.750000,75.000000,33.250000,33.000000,6.750000,0.775000,19.750000,70.750000,100.750000
max,60.000000,100.000000,45.000000,40.000000,9.000000,1.000000,21.000000,75.000000,135.000000

In [5]:
import pandas as pd

df_processed = pd.read_csv("../data/processed/quito_air_quality_processed.csv")
df_processed.head()

,datetime,station,pm25,pm10,no2,o3,so2,co,temperature,humidity,aqi,hour,dayofweek,month,is_weekend,target
0,2026-01-01 08:00:00,Centro,12.0,25.0,18.0,20.0,4.0,0.4,15.0,72.0,42.0,8,3,1,0,buena
1,2026-01-01 09:00:00,Centro,18.0,30.0,20.0,22.0,5.0,0.5,16.0,70.0,55.0,9,3,1,0,moderada
2,2026-01-01 10:00:00,Centro,35.0,60.0,28.0,30.0,6.0,0.7,18.0,65.0,88.0,10,3,1,0,moderada
3,2026-01-01 11:00:00,Centro,55.0,90.0,40.0,38.0,8.0,0.9,19.0,60.0,120.0,11,3,1,0,mala
4,2026-01-01 12:00:00,Cotocollao,10.0,20.0,15.0,19.0,3.0,0.3,17.0,75.0,38.0,12,3,1,0,buena

In [6]:
df_processed.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 16 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   datetime     10 non-null     str
 1   station      10 non-null     str
 2   pm25         10 non-null     float64
 3   pm10         10 non-null     float64
 4   no2          10 non-null     float64
 5   o3           10 non-null     float64
 6   so2          10 non-null     float64
 7   co           10 non-null     float64
 8   temperature  10 non-null     float64
 9   humidity     10 non-null     float64
 10  aqi          10 non-null     float64
 11  hour         10 non-null     int64
 12  dayofweek    10 non-null     int64
 13  month        10 non-null     int64
 14  is_weekend   10 non-null     int64
 15  target       10 non-null     str
dtypes: float64(9), int64(4), str(3)
memory usage: 1.4 KB

In [7]:
df_processed["target"].value_counts()

target
moderada    4
buena       3
mala        3
Name: count, dtype: int64

In [8]:
df_processed.columns

Index(['datetime', 'station', 'pm25', 'pm10', 'no2', 'o3', 'so2', 'co',
       'temperature', 'humidity', 'aqi', 'hour', 'dayofweek', 'month',
       'is_weekend', 'target'],
      dtype='str')